// Creating a promise
// const myPromise = new Promise((resolve, reject) => {
//     // Perform an asynchronous operation
//     setTimeout(() => {
//       const randomNumber = Math.random();
      
//       if (randomNumber < 0.5) {
//         // Resolve the promise with a value
//         resolve(randomNumber);
//       } else {
//         // Reject the promise with an error
//         reject('Random number is too high');
//       }
//     }, 1000); // Simulating an asynchronous operation that takes 1 second
//   });
  
//   // Using the promise
//   myPromise
//     .then((result) => {
//       console.log('Promise resolved with result:', result);
//     })
//     .catch((error) => {
//       console.error('Promise rejected with error:', error);
//     });


//Example



  